version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.0
      
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "e0:f1:7b:8c:b1:4c:49:6f:b9:bd:af:84:6d:dd:93:cb"      
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cp .circleci/mock.env.json .env.json
      - run: sudo npm install -g grunt sass
      - run: grunt build
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              git config credential.helper 'cache --timeout=120'
              git config user.email "ericnakagawa@gmail.com"
              git config user.name "CircleCI Bot"
              git add .
              git commit -m "Deploying theme build via CircleCI"
              git push -q git@github.com:pytorch/pytorch_sphinx_theme.git master
            fi
